mapping = {
    "UniTune: Text-Driven Image Editing by Fine Tuning an Image Generation Model on a Single Image": "UniTune",
    "DiffEdit: Diffusion-based semantic image editing with mask guidance": "DiffEdit",
    "RePaint: Inpainting using Denoising Diffusion Probabilistic Models": "RePaint",
    "DiffusionCLIP: Text-Guided Diffusion Models for Robust Image Manipulation": "DiffusionCLIP",
    "Imagic: Text-Based Real Image Editing with Diffusion Models": "Imagic",
    "SDEdit: Guided Image Synthesis and Editing with Stochastic Differential Equations": "SDEdit",
    "Multimodal Explanations: Justifying Decisions and Pointing to the Evidence": "Multimodal Explanations",
    "DeepVoting: A Robust and Explainable Deep Network for Semantic Part Detection under Partial Occlusion": "DeepVoting",
    "Diffusion Models already have a Semantic Latent Space": "ASYRP",
    "UnitBox: An Advanced Object Detection Network": "UnitBox",
    "Show, Attend and Tell: Neural Image Caption Generation with Visual Attention": "Show, Attend and Tell",
    "Attentional Bottleneck: Towards an Interpretable Deep Driving Network": "Attentional Bottleneck",
    "VoxelNet: End-to-End Learning for Point Cloud Based 3D Object Detection": "VoxelNet",
    "PointPillars: Fast Encoders for Object Detection from Point Clouds": "PointPillars",
    "Deep Variational Information Bottleneck": "Deep VIB",
    "InfoBot: Transfer and Exploration via the Information Bottleneck": "InfoBot",
    "Sharp U-Net: Depthwise Convolutional Network for Biomedical Image Segmentation": "Sharp U-Net",
    "SMU-Net: Style matching U-Net for brain tumor segmentation with missing modalities": "SMU-Net",
    "GradNorm: Gradient Normalization for Adaptive Loss Balancing in Deep Multitask Networks": "GradNorm",
    "Cross-stitch Networks for Multi-task Learning": "Cross-Stitch",
    "Gradient Surgery for Multi-Task Learning": "PCGrad",
    "Actor-Mimic: Deep Multitask and Transfer Reinforcement Learning": "Actor-Mimic",
    "Plenoxels: Radiance Fields without Neural Networks": "Plenoxels",
    "Point-NeRF: Point-based Neural Radiance Fields": "Point-NeRF",
    "NeX: Real-time View Synthesis with Neural Basis Expansion": "NeX",
    "NeRF in the Wild: Neural Radiance Fields for Unconstrained Photo Collections": "NeRF in the Wild",
    "GRAF: Generative Radiance Fields for 3D-Aware Image Synthesis": "GRAF",
    "NeRF: Representing Scenes as Neural Radiance Fields for View Synthesis": "NeRF",
    "Neural Volumes: Learning Dynamic Renderable Volumes from Images": "Neural Volumes",
    "AtlasNet: A Papier-Mâché Approach to Learning 3D Surface Generation": "AtlasNet",
    "DeepSDF: Learning Continuous Signed Distance Functions for Shape Representation": "DeepSDF",
    "NeRF--: Neural Radiance Fields Without Known Camera Parameters": "NeRF--",
    "An Image is Worth One Word: Personalizing Text-to-Image Generation using Textual Inversion": "An Image is Worth One Word",
    # Class Activation Maps (CAMs)
    "Learning Deep Features for Discriminative Localization": "CAM",
    "Grad-CAM: Visual Explanations from Deep Networks via Gradient-based Localization": "Grad-CAM",
    "Grad-CAM++: Improved Visual Explanations for Deep Convolutional Networks": "Grad-CAM++",
    # Denoising Diffusion Probabilistic Models (DDPMs)
    "Denoising Diffusion Probabilistic Models": "DDPM",
    "Denoising Diffusion Implicit Models": "DDIM",
    "gDDIM: Generalized denoising diffusion implicit models": "gDDIM",
    "ILVR: Conditioning Method for Denoising Diffusion Probabilistic Models": "ILVR",
    "Improved Denoising Diffusion Probabilistic Models": "Improved DDPM",
    "Pyramidal Denoising Diffusion Probabilistic Models": "Pyramidal DDPM",
    "AT-DDPM: Restoring Faces degraded by Atmospheric Turbulence using Denoising Diffusion Probabilistic Models": "AT-DDPM",
    "T2V-DDPM: Thermal to Visible Face Translation using Denoising Diffusion Probabilistic Models": "T2V-DDPM",
    "Learning Fast Samplers for Diffusion Models by Differentiating Through Sample Quality": "Differentiable Diffusion Sampler Search",
}
