mapping = {
    "UniTune: Text-Driven Image Editing by Fine Tuning an Image Generation Model on a Single Image": "UniTune",
    "ILVR: Conditioning Method for Denoising Diffusion Probabilistic Models": "ILVR",
    "DiffEdit: Diffusion-based semantic image editing with mask guidance": "DiffEdit",
    "RePaint: Inpainting using Denoising Diffusion Probabilistic Models": "RePaint",
    "DiffusionCLIP: Text-Guided Diffusion Models for Robust Image Manipulation": "DiffusionCLIP",
    "Imagic: Text-Based Real Image Editing with Diffusion Models": "Imagic",
    "SDEdit: Guided Image Synthesis and Editing with Stochastic Differential Equations": "SDEdit",
    "Grad-CAM: Visual Explanations from Deep Networks via Gradient-based Localization": "Grad-CAM",
    "Multimodal Explanations: Justifying Decisions and Pointing to the Evidence": "Multimodal Explanations",
    "DeepVoting: A Robust and Explainable Deep Network for Semantic Part Detection under Partial Occlusion": "DeepVoting",
    "Diffusion Models already have a Semantic Latent Space": "ASYRP",
    "Denoising Diffusion Probabilistic Models": "DDPM",
    "Denoising Diffusion Implicit Models": "DDIM",
    "UnitBox: An Advanced Object Detection Network": "UnitBox",
    "Show, Attend and Tell: Neural Image Caption Generation with Visual Attention": "Show, Attend and Tell",
    "Attentional Bottleneck: Towards an Interpretable Deep Driving Network": "Attentional Bottleneck",
    "Learning Deep Features for Discriminative Localization": "CAM",
    "VoxelNet: End-to-End Learning for Point Cloud Based 3D Object Detection": "VoxelNet",
    "PointPillars: Fast Encoders for Object Detection from Point Clouds": "PointPillars",
    "Deep Variational Information Bottleneck": "Deep VIB",
    "InfoBot: Transfer and Exploration via the Information Bottleneck": "InfoBot",
}
